# DO NOT EDIT THIS FILE!
#
# Python module Calculator generated by omniidl

import omniORB
omniORB.updateModule("Calculator")

# ** 1. Stub files contributing to this module
import calc_idl

# ** 2. Sub-modules

# ** 3. End
