# DO NOT EDIT THIS FILE!
#
# Python module Calculator__POA generated by omniidl

import omniORB
omniORB.updateModule("Calculator__POA")

# ** 1. Stub files contributing to this module
import calc_idl

# ** 2. Sub-modules

# ** 3. End
